### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by kentbulza** [ai-robots-txt/ai.robots.txt#12]
Should come include Apache and Nginx rewrites for the bots that don't respect. Bytespider doesn't seem to respect. Or they only read robots.txt infrequently...I dunno which.

**Comment by ZicklePop** [comment]
I've taken to [rewriting them](https://paste.melanie.lol/no-ai--next.config.js) to a 10gb binary file at `https://hil-speed.hetzner.com/10GB.bin` :)

**Comment by cdransf** [comment]
@kentbulza I totally blanked on this, but we do have rewrites here: https://github.com/ai-robots-txt/ai.robots.txt/tree/e152c110c5ca86389976f0f20866735e72857e1b/servers

If you encounter issues with them, I'm happy to pursue further. Cheers!
