### ISSUE TITLE
Add bots blocked by Tumblr

### ISSUE THREAD

**Issue by corbindavenport** [ai-robots-txt/ai.robots.txt#19]
I was looking at the robots.txt on my Tumblr-hosted blog: https://blog.corbin.io/robots.txt

There are a few bots Tumblr is blocking that aren't in this list:

```
# Common Crawl's crawler
User-agent: CCBot
Disallow: /

# SentiBot's crawler
User-agent: sentibot
Disallow: /

# ImageSift's AI crawler
User-agent: ImagesiftBot
Disallow: /

# TurnitinBot crawler
User-agent: TurnitinBot
Disallow: /
```

Not sure if all of these should be blocked or just some of them.

**Comment by cdransf** [comment]
Hey! Thanks for calling this out! We've got `CCBot` included and [I added `ImageSiftBot`](https://github.com/ai-robots-txt/ai.robots.txt/commit/0ca6bce87ec6ec21e42fb7179ce1a0bf5a0ecc34). I don't believe `sentibot` or `TurnitinBot` are strictly related to AI so I'll hold off for now (I believe the former is sentiment analysis and the latter is for plagiarism detection).

**Comment by marek22k** [comment]
If I'm right, the sentibot belongs to https://sentione.com/ and that looks a bit like AI.
