### ISSUE TITLE
If you block AdsBot-Google, google ads won't show your ads?

### ISSUE THREAD

**Issue by jackusay** [ai-robots-txt/ai.robots.txt#20]
If you block [AdsBot-Google](https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers), google ads won't show your ads?
Can anyone confirm this?

If so, maybe add some warning in docs?

**Comment by simoncox** [comment]
Think you might need to clarify that slightly - google ads won't show **your** ads? Think you probably mean "show ads on your site." (Thats a assumption and I apologise if I have misread.)

Anyway, my understanding is that if Google AdsBot cannot crawl a site then it will not know what content is on there and I believe it needs to do that to understand what markets would be looking at that content so it can show ads on there that would be suitable for those markets.  

So if you have Google Ads on your site I would be careful with any blocking as some advertisers are bound to be using AI to help them understand how their ads are performing.  

Good call as there is probably a lot more nuance in this. And we are all probably too late anyway.

**Comment by jackusay** [comment]
> google ads won't show your ads?

I mean if you want to display your ads (that link to your site) on Google's `Search Engine Results Pages`, then blocking `AdsBot-Google` is possibly not a good idea.

(This may also affect ads within your website, but I'm not sure, as I don't have any ads on my site.)

**Comment by simoncox** [comment]
Ah yes - that makes sense!

**Comment by cdransf** [comment]
I’d be ok to remove this agent if you’d like to issue a pull request. `Google-Extended` is the most important to block and explicitly AI related.

**Comment by cdransf** [comment]
Updated here https://github.com/ai-robots-txt/ai.robots.txt/commit/af525789653bda55d80fb17dc3f51a720658d938 — also added some additional `GoogleOther` bots that are leveraged for internal use by Google.
