### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by glyn** [ai-robots-txt/ai.robots.txt#3]
We could prime some questions in a FAQ from the [hacker news discussion](https://news.ycombinator.com/item?id=39849985). The main one is along the lines of "Why would an AI web crawler respect robots.txt?"

If we wanted to be brave, we could enable a wiki for this repo!

**Comment by cdransf** [comment]
Began outlining some questions and answers here: https://github.com/ai-robots-txt/ai.robots.txt/wiki/Frequently-asked-questions

**Comment by gene1wood** [comment]
@glyn Cory moved the FAQ from the wiki into a file in 6c596a50ea9ca620e4f48a400d8c3bc817a7bdb0 if you want to PR you suggested question and answer

**Comment by glyn** [comment]
Done: https://github.com/ai-robots-txt/ai.robots.txt/pull/31. Thanks.
