### ISSUE TITLE
ImageSift AI or not?

### ISSUE THREAD

**Issue by glyn** [ai-robots-txt/ai.robots.txt#30]
Reading ImageSift's [about page](https://imagesift.com/about), this seems to be an image search site rather than AI. If so, then ImageSift is out of scope for this project.

/cc @jsheard 

PS. Apologies for not raising this until now. I've been on holiday for a few days.

**Comment by jsheard** [comment]
Imagesift itself is an image search site, but their parent company offers genAI products: https://thehive.ai/apis/image-generation

They don't list any Hive-specific user agents so I think it is safe to assume the Imagesift crawler is doing double duty as an AI crawler.

**Comment by glyn** [comment]
Ok, thanks @jsheard. Let's assume the crawler is used for AI purposes until such time as the about page explicitly denies that.
