### ISSUE TITLE
Mention Spawning AI’s `ai.txt` file

### ISSUE THREAD

**Issue by yeskunall** [ai-robots-txt/ai.robots.txt#5]
tl;dr: independent body suggests adding new file to site root directory to ask organizations that use AI for text and data mining (TDM) to __NOT__ use site data for training purposes.

From their [FAQ](https://spawning.ai/rightsholders-faq):

> An ai.txt file is a simple text file placed in the root directory (or .well-known/) of your website that communicates with data miners. It provides instructions on whether the text and media files hosted on your domain can be used to train commercial AI models.

An example file I [created](https://spawning.ai/ai-txt#create):

```txt
# Spawning AI
# Prevent datasets from using the following file types

User-Agent: *
Disallow: /
Disallow: *
```

__PS__: Thanks for this project 💖

---
Resources:

- [ai.txt: A new way for websites to set permissions for AI](https://spawning.substack.com/p/aitxt-a-new-way-for-websites-to-set)
- [About Spawning AI](https://spawning.ai/about)

**Comment by cdransf** [comment]
Just updated the readme and added an ai.txt to the repository. Cheers!
