### ISSUE TITLE
Help populating table-of-bot-metrics.md

### ISSUE THREAD

**Issue by cdransf** [ai-robots-txt/ai.robots.txt#7]
Help populate the [table-of-bot-metrics.md](https://github.com/ai-robots-txt/ai.robots.txt/blob/main/table-of-bot-metrics.md) to clarify bot activity.

**Comment by corbindavenport** [comment]
I can try working on this :) I'll submit a PR when I get somewhere.

**Comment by cdransf** [comment]
Looks like we're in good shape on this one for now. ✅
