### ISSUE TITLE
Add img2dataset

### ISSUE THREAD

**Issue by robrwo** [ai-robots-txt/ai.robots.txt#9]
[img2dataset](https://github.com/rom1504/img2dataset) is software that spiders sites for AI training. It's not run by a specific company so hits can come from anywhere.

It claims to honor `robots.txt` with the "img2dataset" user agent token, and X-Robots-Tag or HTML `<meta>` directives "noai" and "noimageai".

**Comment by cdransf** [comment]
Updated across the repository. Thank you!
